name: Deployment
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: patrick.mkay.dev
        username: root
        key: ${{ secrets.KEY }}
        script: cd /mnt/frontend-3/patrick.mkay.dev && git pull && yarn && yarn build